version: '3.1'
services:
  serverexpress:
    container_name: express
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
    - "3000:3000"
    tty: true
    restart: unless-stopped
  database:
      image: mysql:latest
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: test
      ports:
        - 3306:3306